//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POC.WPF.FilaDebitoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DebitarPrestacaoCommand", Namespace="http://schemas.datacontract.org/2004/07/POC.WCF.Models")]
    [System.SerializableAttribute()]
    public partial class DebitarPrestacaoCommand : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SequencialOperacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SequencialPrestacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SequencialOperacao {
            get {
                return this.SequencialOperacaoField;
            }
            set {
                if ((this.SequencialOperacaoField.Equals(value) != true)) {
                    this.SequencialOperacaoField = value;
                    this.RaisePropertyChanged("SequencialOperacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SequencialPrestacao {
            get {
                return this.SequencialPrestacaoField;
            }
            set {
                if ((this.SequencialPrestacaoField.Equals(value) != true)) {
                    this.SequencialPrestacaoField = value;
                    this.RaisePropertyChanged("SequencialPrestacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResult", Namespace="http://schemas.datacontract.org/2004/07/POC.WCF.Models")]
    [System.SerializableAttribute()]
    public partial class ServiceResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private POC.WPF.FilaDebitoService.Erro ErroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public POC.WPF.FilaDebitoService.Erro Erro {
            get {
                return this.ErroField;
            }
            set {
                if ((object.ReferenceEquals(this.ErroField, value) != true)) {
                    this.ErroField = value;
                    this.RaisePropertyChanged("Erro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Erro", Namespace="http://schemas.datacontract.org/2004/07/POC.WCF.Models")]
    [System.SerializableAttribute()]
    public partial class Erro : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DebitarPrestacaoResult", Namespace="http://schemas.datacontract.org/2004/07/POC.WCF.Models")]
    [System.SerializableAttribute()]
    public partial class DebitarPrestacaoResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private POC.WPF.FilaDebitoService.Erro ErroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NSUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SequencialPrestacaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public POC.WPF.FilaDebitoService.Erro Erro {
            get {
                return this.ErroField;
            }
            set {
                if ((object.ReferenceEquals(this.ErroField, value) != true)) {
                    this.ErroField = value;
                    this.RaisePropertyChanged("Erro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NSU {
            get {
                return this.NSUField;
            }
            set {
                if ((this.NSUField.Equals(value) != true)) {
                    this.NSUField = value;
                    this.RaisePropertyChanged("NSU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SequencialPrestacao {
            get {
                return this.SequencialPrestacaoField;
            }
            set {
                if ((this.SequencialPrestacaoField.Equals(value) != true)) {
                    this.SequencialPrestacaoField = value;
                    this.RaisePropertyChanged("SequencialPrestacao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FilaDebitoService.IFilaDebito")]
    public interface IFilaDebito {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilaDebito/Dispatch", ReplyAction="http://tempuri.org/IFilaDebito/DispatchResponse")]
        POC.WPF.FilaDebitoService.ServiceResult Dispatch(POC.WPF.FilaDebitoService.DebitarPrestacaoCommand cmd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilaDebito/Dispatch", ReplyAction="http://tempuri.org/IFilaDebito/DispatchResponse")]
        System.Threading.Tasks.Task<POC.WPF.FilaDebitoService.ServiceResult> DispatchAsync(POC.WPF.FilaDebitoService.DebitarPrestacaoCommand cmd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilaDebito/Listener", ReplyAction="http://tempuri.org/IFilaDebito/ListenerResponse")]
        POC.WPF.FilaDebitoService.ServiceResult Listener(POC.WPF.FilaDebitoService.DebitarPrestacaoResult res);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilaDebito/Listener", ReplyAction="http://tempuri.org/IFilaDebito/ListenerResponse")]
        System.Threading.Tasks.Task<POC.WPF.FilaDebitoService.ServiceResult> ListenerAsync(POC.WPF.FilaDebitoService.DebitarPrestacaoResult res);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFilaDebitoChannel : POC.WPF.FilaDebitoService.IFilaDebito, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FilaDebitoClient : System.ServiceModel.ClientBase<POC.WPF.FilaDebitoService.IFilaDebito>, POC.WPF.FilaDebitoService.IFilaDebito {
        
        public FilaDebitoClient() {
        }
        
        public FilaDebitoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FilaDebitoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FilaDebitoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FilaDebitoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public POC.WPF.FilaDebitoService.ServiceResult Dispatch(POC.WPF.FilaDebitoService.DebitarPrestacaoCommand cmd) {
            return base.Channel.Dispatch(cmd);
        }
        
        public System.Threading.Tasks.Task<POC.WPF.FilaDebitoService.ServiceResult> DispatchAsync(POC.WPF.FilaDebitoService.DebitarPrestacaoCommand cmd) {
            return base.Channel.DispatchAsync(cmd);
        }
        
        public POC.WPF.FilaDebitoService.ServiceResult Listener(POC.WPF.FilaDebitoService.DebitarPrestacaoResult res) {
            return base.Channel.Listener(res);
        }
        
        public System.Threading.Tasks.Task<POC.WPF.FilaDebitoService.ServiceResult> ListenerAsync(POC.WPF.FilaDebitoService.DebitarPrestacaoResult res) {
            return base.Channel.ListenerAsync(res);
        }
    }
}
