//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POC.FRM.FilaDebitoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FilaDebitoService.IFilaDebito")]
    public interface IFilaDebito {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilaDebito/Dispatch", ReplyAction="http://tempuri.org/IFilaDebito/DispatchResponse")]
        POC.DTO.ServiceResult Dispatch(int sequencialPrestacao, string callbackURL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilaDebito/Dispatch", ReplyAction="http://tempuri.org/IFilaDebito/DispatchResponse")]
        System.Threading.Tasks.Task<POC.DTO.ServiceResult> DispatchAsync(int sequencialPrestacao, string callbackURL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilaDebito/Listener", ReplyAction="http://tempuri.org/IFilaDebito/ListenerResponse")]
        POC.DTO.ServiceResult Listener(int sequencialPrestacao, bool pago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilaDebito/Listener", ReplyAction="http://tempuri.org/IFilaDebito/ListenerResponse")]
        System.Threading.Tasks.Task<POC.DTO.ServiceResult> ListenerAsync(int sequencialPrestacao, bool pago);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFilaDebitoChannel : POC.FRM.FilaDebitoService.IFilaDebito, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FilaDebitoClient : System.ServiceModel.ClientBase<POC.FRM.FilaDebitoService.IFilaDebito>, POC.FRM.FilaDebitoService.IFilaDebito {
        
        public FilaDebitoClient() {
        }
        
        public FilaDebitoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FilaDebitoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FilaDebitoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FilaDebitoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public POC.DTO.ServiceResult Dispatch(int sequencialPrestacao, string callbackURL) {
            return base.Channel.Dispatch(sequencialPrestacao, callbackURL);
        }
        
        public System.Threading.Tasks.Task<POC.DTO.ServiceResult> DispatchAsync(int sequencialPrestacao, string callbackURL) {
            return base.Channel.DispatchAsync(sequencialPrestacao, callbackURL);
        }
        
        public POC.DTO.ServiceResult Listener(int sequencialPrestacao, bool pago) {
            return base.Channel.Listener(sequencialPrestacao, pago);
        }
        
        public System.Threading.Tasks.Task<POC.DTO.ServiceResult> ListenerAsync(int sequencialPrestacao, bool pago) {
            return base.Channel.ListenerAsync(sequencialPrestacao, pago);
        }
    }
}
